# Generated by Django 5.2 on 2025-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('1', 'Kitap'), ('2', 'Gollanma'), ('3', 'Okuw maksatnama'), ('4', 'Ylmy is'), ('5', 'Referat'), ('6', 'Diplom is'), ('7', 'Sapak yazgysy')], default='1', max_length=50),
        ),
    ]
