# Generated by Django 5.2 on 2025-06-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
    ]
