# Generated by Django 5.2 on 2025-08-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_allow_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
